***( Case when there is a crash without specifying 
explicitly a gap or positions.)
 mod SCENARIO-CROSSING is
 inc SCENARIO-TEMPLATE-VEH-PED-V2 .
 
*** Define resolveKB
*** Scenario where the vehicle in front is in
*** constant speed, while the vehicle in the back is following.
 vars numVars stp : Nat .
vars b1 b2 b3 : Bool .
var conf : Conf .
var env : Env .
var lkb : KB .
var id0 : Id .
vars ff0 ff1 ff2 ff3 : SymTerm .
vars t t1 t2 n t3 t4 k : Nat .
vars cond cond3 : Boolean . 
vars smtRes1 smtRes2 smtRes3 : SmtCheckResult .
var dtVal : Real .


eq lkb1 = 
    class(v(1),veh) 
    (atloc(v(1),loc(vposx,vposy)) @ 0)
    (speed(v(1), vvel) @ 0) 
    (dir(v(1),loc(vinix,viniy),
              loc(vtarx,vtary),vmag) @ 0) 
    (maxAcc(v(1),maxacc1)) 
    (maxDec(v(1),maxdec1))
    (mode(v(1),leading(none)) @ 0)
    velb(v(1),vellb1,velub1)
    (accel(v(1),acc1) @ 0)
    (pedCaution(v(1),safe) @ 0)
    gapSafety(v(1),safer,safe,bad) .

eq lkbPed = 
    class(v(2),pedestrian) 
    (atloc(v(2),loc(pposx,pposy)) @ 0)
    (speed(v(2), pvel) @ 0) 
    (dir(v(2),loc(pinix,piniy),
              loc(ptarx,ptary),pmag) @ 0)
    velb(v(2),vellb2,velub2)
    (accel(v(2),acc2) @ 0)
    maxAcc(v(2),maxacc2)
    maxDec(v(2),maxdec2) .

eq ekb(numVars,cond,stp) =
    clock(0) stop(stp)
    lkb1 lkbPed
    tickSize(dt)
    (velb(v(1),vellb1,velub1))
    (velb(v(2),vellb2,velub2))
    constraint(numVars,cond) .

--- red ekb(35,true,3) .

*** Vehicle moving in a straight line on axis Y.
*** Speed bounds
*** Positive Positions
ops basicCondPedX basicCondLine : -> Boolean .
eq basicCondPedX = 
  vposx === 5/1 and vposy >= 0/1 and
  pposx === pinix and pposy === piniy and
  pinix >= 0/1  and piniy >= vposy and
  ptarx === 10/1  and ptary === piniy and
  pmag === (ptarx - pinix) and 
  (vvel >= vellb1) and (vvel <= velub1) and
  (pvel >= vellb2) and (pvel <= velub2) and
  (vinix === 0/1) and (viniy === 0/1) and
  (vtarx === 0/1) and (vtary === 1/1) and
  (acc1 >= maxdec1) and (acc1 <= maxacc1) and
  (acc2 >= maxdec2) and (acc2 <= maxacc2) and
  (vmag === 1/1) .

eq basicCondLine 
 = vposx === 5/1 and vposy >= 0/1 and
  pposx === pinix and pposy === piniy and
  pinix >= 0/1  and piniy >= vposy and
  ptarx === 10/1  and ptary >= vposy and
  ((pmag * pmag) === (ptary - piniy) * (ptary - piniy) 
                + (ptarx - pinix) * (ptarx - pinix)) and 
  (vvel >= vellb1) and (vvel <= velub1) and
  (pvel >= vellb2) and (pvel <= velub2) and
  (vinix === 0/1) and (viniy === 0/1) and
  (vtarx === 0/1) and (vtary === 1/1) and
  (acc1 >= maxdec1) and (acc1 <= maxacc1) and
  (acc2 >= maxdec2) and (acc2 <= maxacc2) and
  (vmag === 1/1) .

op bounds : Real -> Boolean .
eq bounds(dtVal) = 
 (vellb1 === 2/1) and (velub1 === 10/1) and 
 (vellb2 === 1/2) and (velub2 === 3/2) and
 (maxacc1 === 6/1) and (maxdec1 === - 2/1) and 
 (maxacc2 === 1/4) and (maxdec2 === - 1/4) and 
 (safer === 3/1) and (safe === 2/1) and 
 (bad === 1/1) and (dt === dtVal) 
  and (pedSDist === 50/1) .

ops asysPedXLine asysPedXLineFixed : Nat Real -> ASystem .
eq asysPedXLine(stp,dtVal) 
  = asysCrossing(35,basicCondPedX and bounds(dtVal),stp) .
eq asysPedXLineFixed(stp,dtVal) 
 = fixDynamics(asysPedXLine(stp,dtVal),getIds(asysPedXLine(stp,dtVal))) .

ops asysPedStraight asysPedStraightFixed : Nat Real -> ASystem .
eq asysPedStraight(stp,dtVal) 
  = asysCrossing(35,basicCondLine and bounds(dtVal),stp) .
eq asysPedStraightFixed(stp,dtVal) 
 = fixDynamics(asysPedStraight(stp,dtVal),getIds(asysPedStraight(stp,dtVal))) .

endm

eof


*** Notice that checkTimeDur is still calling timestep and not timesteps.
*** However checkTimeDurSPtoSP1Asys calls timesteps.
--- maudez3 load-pedestrian.maude
*** Check time property for dt = 1/10
red checkTimeDur(asysPedXLine(3,1/10)) .

red checkTimeDurSPtoSP1(saferSP,saferSP,asysPedXLineFixed(3,1/10),dt) .
rewrites: 123672 in 9992083ms cpu (10010505ms real) (12 rewrites/second)
result Bool: (true).Bool

red checkTimeDurSPtoSP1(saferSP,safeSP,asysPedXLineFixed(3,1/10),dt) .

red checkTimeDurSPtoSP1Asys(saferSP,safeSP,asysPedXLineFixed(3,1/10),dt) .
Started 15:24.

red checkTimeDurSPtoSP1(safeSP,safeSP,asysPedXLineFixed(3,1/10),dt) .
red checkTimeDurSPtoSP1(safeSP,unsafeSP,asysPedXLineFixed(3,1/10),dt) .
red checkTimeDurSPtoSP1(unsafeSP,badSP,asysPedXLineFixed(3,1/10),dt) .
red checkTimeDurSPtoSP1(unsafeSP,unsafeSP,asysPedXLineFixed(3,1/10),dt) .
red checkTimeDurSPtoSP1(unsafeSP,safeSP,asysPedXLineFixed(3,1/10),dt) .
red checkTimeDurSPtoSP1(badSP,badSP,asysPedXLineFixed(3,1/10),dt) .
red checkTimeDurSPtoSP1(badSP,unsafeSP,asysPedXLineFixed(3,1/10),dt) .

-------------------------------------

*** This is true because there are no transitions from safer to safer
red checkTimeDurSPtoSP1(saferSP,saferSP,asysPedXLineFixed(3,100/1),dt) .
rewrites: 4862 in 5294ms cpu (5324ms real) (918 rewrites/second)
result Bool: (true).Bool
*** This is true because there are no transitions from safer to safe
red checkTimeDurSPtoSP1(saferSP,safeSP,asysPedXLineFixed(3,100/1),dt) .
    asysPedXLineFixed(3, 100/1), dt) .
rewrites: 4832 in 144ms cpu (146ms real) (33476 rewrites/second)
result Bool: (true).Bool

---------------------------------------------
--- maudez3 load-pedestrian-timesteps.maude
red checkTimeDur(asfixed) .


op condGround : -> Boolean .

op cond1 : -> Boolean .
eq cond1 = 
     vposx === 5/1 and
     vposy === 0/1 and
     pposx === pinix and
     pposy === piniy and
     vvel === 5/1 / tickSize and
     pvel === 2/1 / tickSize and
     pinix === 0/1 and
     piniy <= 25/1 and
     piniy >= 20/1 and
     ptarx === 10/1 and
     ptary === 25/1 and
     pedSDist === 50/1 and
     vinix === 5/1 and
     viniy === 0/1 and
     vtarx === 5/1 and
     vtary === 1/1 and
     ((pmag * pmag) === (ptary - piniy) * (ptary - piniy) 
                + (ptarx - pinix) * (ptarx - pinix)) and
     vmag === 1/1 and 
     safer === 10/1 and 
     safe === 5/1  and 
     vellb1 === 1/1 / tickSize and
     velub1 === 7/1 / tickSize and 
     vellb2 === 1/1 / tickSize and
     velub2 === 2/1 / tickSize and 
     maxacc1 === 2/1 / tickSize  and
     maxdec1 === 2/1 / tickSize and
     maxacc2 === 0/1 / tickSize  and
     maxdec2 === 0/1 / tickSize .

  ops as1 as1safe : Nat -> ASystem .






